### ISSUE TITLE
Course progress indicators on the dash board are displaced

### ISSUE THREAD

**Issue by phish108** [BLC-HTWChur/htwboost#101]
The process indicators and their placeholders on the dashboard are displaced. They now overlap with the course title.

**Comment by hakunana** [comment]
@phish108 
Browser and version please. 
So far only seen on IE10

**Comment by hakunana** [comment]
known issues with IE and Bootstrap 4

Bootstrap 4 grid system will not work on IE because of missing flex-recognition. https://github.com/twbs/bootstrap/issues/17310
