### ISSUE TITLE
Installing of Plugin v2.0 beta fails 

### ISSUE THREAD

**Issue by rogerbaba** [BLC-HTWChur/htwboost#109]
Debug info: core/toolbar
Error code: filenotfound
Stack trace:
line 125 of /lib/classes/output/mustache_template_finder.php: moodle_exception thrown
line 54 of /lib/classes/output/mustache_filesystem_loader.php: call to core\output\mustache_template_finder::get_template_filepath()
line 99 of /lib/mustache/src/Mustache/Loader/FilesystemLoader.php: call to core\output\mustache_filesystem_loader->getFileName()
line 82 of /lib/mustache/src/Mustache/Loader/FilesystemLoader.php: call to Mustache_Loader_FilesystemLoader->loadFile()
line 657 of /lib/mustache/src/Mustache/Engine.php: call to Mustache_Loader_FilesystemLoader->load()
line 170 of /lib/outputrenderers.php: call to Mustache_Engine->loadTemplate()
line 65 of /theme/htwboost/classes/output/core_renderer.php: call to renderer_base->render_from_template()
line 253 of /theme/htwboost/classes/output/core_renderer.php: call to theme_htwboost\output\core_renderer->render_from_template()
line 164 of /theme/htwboost/classes/output/core_renderer.php: call to theme_htwboost\output\core_renderer->toolbar()
line 219 of /lib/mustache/src/Mustache/Context.php: call to theme_htwboost\output\core_renderer->full_header()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 76 of /var/www/moodle/data/localcache/mustache/1530014274/htwboost/__Mustache_211b794e3336b665e2fc5fc001c93c6a.php: call to Mustache_Context->findDot()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_211b794e3336b665e2fc5fc001c93c6a->renderInternal()
line 177 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 65 of /theme/htwboost/classes/output/core_renderer.php: call to renderer_base->render_from_template()
line 55 of /theme/htwboost/layout/columns2.php: call to theme_htwboost\output\core_renderer->render_from_template()
line 1273 of /lib/outputrenderers.php: call to include()
line 1203 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 448 of /lib/outputrenderers.php: call to core_renderer->header()
line 295 of /admin/renderer.php: call to plugin_renderer_base->__call()
line 889 of /admin/index.php: call to core_admin_renderer->admin_notifications_page()

**Comment by hakunana** [comment]
@rogerbaba Was geht denn nicht?

**Comment by rogerbaba** [comment]
nach der Installation kommt gleich dieser Fehler und es funktioniert nix. Offenbar fehlt irgendeine Datei.
Versuch mal rauszufinden welche.

**Comment by rogerbaba** [comment]
Directory classes have to be deleted in the reop
