### ISSUE TITLE
warning auf website admin / search.php

### ISSUE THREAD

**Issue by hakunana** [BLC-HTWChur/htwboost#11]
Fehlermeldung ist oben im debug angezeigt: 

extralocations parameter in get_string() is not supported any more, please use standard lang locations only.
line 7053 of /lib/moodlelib.php: call to debugging()
line 53 of /theme/htwchur/settings.php: call to get_string()
line 51 of /admin/settings/appearance.php: call to include()
line 8002 of /lib/adminlib.php: call to require()
line 15 of /admin/search.php: call to admin_get_root()

**Comment by phish108** [comment]
unrelated. The old theme had an invalid function in its settings. 
Fixed there.
