### ISSUE TITLE
Active Role distorts the navbar

### ISSUE THREAD

**Issue by phish108** [BLC-HTWChur/htwboost#3]
If a user switches the role using the "switch role to ..." function, then the new role is displayed under the username.

This role information distorts the status bar. 

The role information should be arranged in a way that does not distort the status bar.

**Comment by hakunana** [comment]
![screen shot 2017-10-17 at 14 03 55](https://user-images.githubusercontent.com/282167/31663984-0963957c-b344-11e7-9e40-9ba4358bd9dd.png)


navbar height is changing
