### ISSUE TITLE
mouse overs in the navbar change the layout #minor

### ISSUE THREAD

**Issue by phish108** [BLC-HTWChur/htwboost#43]
Mouse overs on the items in the navbar change the font-weight.
This changes the layout for a few but visible of pixel. 

Mouse overs should change the font but not alter the overall layout.

**Comment by hakunana** [comment]
![screen shot 2017-10-17 at 13 53 17](https://user-images.githubusercontent.com/282167/31663485-8e29a2a8-b342-11e7-90b3-5696fbf5b487.png)
