### ISSUE TITLE
font-size to screen width ratio does not match

### ISSUE THREAD

**Issue by phish108** [BLC-HTWChur/htwboost#52]
Currently the font-size to screen width ratio leads to very long lines that are hard to read. 

The ideally a line contains approx. 70-100 Characters. 

The solutions could be 

- reducing the area that is used for displaying the text
- increasing the font-size to a better screen ratio.

**Comment by hakunana** [comment]
on high resolution the font appears too big
on zoomed out pages it appears too small 

.--> font ratio has to be set according to resolution/screensize --> replace static numbers with em /ratio

**Comment by hakunana** [comment]
font size adjusted. should be fixed
