### ISSUE TITLE
Paddings should be consistent

### ISSUE THREAD

**Issue by phish108** [BLC-HTWChur/htwboost#53]
The paddings of activities and text areas appear not to be the same. 

The padding should of all content areas in courses should be consistent.

**Comment by hakunana** [comment]
explicit example needed to reproduce

**Comment by hakunana** [comment]
example: 
"Nachrichten" top/bottom has different padding than an activity. 
![screen shot 2017-10-17 at 13 17 57](https://user-images.githubusercontent.com/282167/31662177-b4403e70-b33d-11e7-9e31-56f0ca4d8fa3.png)
