### ISSUE TITLE
Top Navigation disappears on mobiles

### ISSUE THREAD

**Issue by phish108** [BLC-HTWChur/htwboost#93]
If a user visits with a mobile client, the responsive UI kicks in and hides some parts of the Info in the header bar. 

User Story:
- User want to get some help: help section is invisible.
- User wants to browse the courses: the link "All Courses"/"Alle Kurse" is invisible

Solution? we need a way for making these links accessible in the mobile UI

**Comment by hakunana** [comment]
Navigation items are being pushed to the footer due to keeping the navigation clean. 

all options are still available
